cat src/App.tsx | awk '
/^\/\/ Marquee/ {
  print "// Studio Section"
  print "const StudioSection = () => {"
  print "  return ("
  print "    <section id=\"studio\" className=\"py-24 px-6 max-w-7xl mx-auto\">"
  print "      <div className=\"text-center mb-16\">"
  print "        <h2 className=\"text-4xl md:text-6xl font-serif italic\">"
  print "          The <span className=\"font-sans font-bold not-italic text-primary\">Studio</span>"
  print "        </h2>"
  print "        <p className=\"mt-4 text-xl font-medium text-foreground/70 max-w-2xl mx-auto\">"
  print "          Where sound meets luxury. Our state-of-the-art creative home in Dubai."
  print "        </p>"
  print "      </div>"
  print ""
  print "      <div className=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6\">"
  print "        {/* Row 1 */}"
  print "        <div className=\"aspect-square rounded-3xl border border-foreground/10 shadow-xl overflow-hidden relative group\">"
  print "          <img src=\"https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80&w=800\" alt=\"Studio Gear\" className=\"w-full h-full object-cover grayscale-[20%] group-hover:grayscale-0 transition-all duration-500 group-hover:scale-105\" />"
  print "        </div>"
  print "        <div className=\"aspect-square rounded-3xl border border-foreground/10 shadow-xl bg-white p-8 flex flex-col justify-center items-center text-center group hover:-translate-y-2 transition-transform duration-300\">"
  print "          <div className=\"w-12 h-12 rounded-full bg-primary/20 flex items-center justify-center mb-6\">"
  print "            <Mic className=\"w-6 h-6 text-primary\" />"
  print "          </div>"
  print "          <h3 className=\"text-2xl font-bold font-sans uppercase tracking-tight mb-4\">FIVE MUSIC Studio</h3>"
  print "          <p className=\"text-foreground/70 font-medium\">Located inside the prestigious FIVE Palm Jumeirah Hotel in Dubai, offering state-of-the-art recording facilities.</p>"
  print "        </div>"
  print "        <div className=\"aspect-square rounded-3xl border border-foreground/10 shadow-xl overflow-hidden relative group\">"
  print "          <img src=\"https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&q=80&w=800\" alt=\"Dubai\" className=\"w-full h-full object-cover grayscale-[20%] group-hover:grayscale-0 transition-all duration-500 group-hover:scale-105\" />"
  print "        </div>"
  print ""
  print "        {/* Row 2 */}"
  print "        <div className=\"aspect-square rounded-3xl border border-foreground/10 shadow-xl bg-foreground text-surface p-8 flex flex-col justify-center items-center text-center group hover:-translate-y-2 transition-transform duration-300 relative overflow-hidden\">"
  print "          <div className=\"absolute inset-0 opacity-10 bg-[url('\''https://images.unsplash.com/photo-1621360841013-c76831f1628f?auto=format&fit=crop&q=80&w=800'\'')] bg-cover mix-blend-overlay\"></div>"
  print "          <div className=\"w-12 h-12 rounded-full bg-white/10 flex items-center justify-center mb-6 relative z-10\">"
  print "            <Star className=\"w-6 h-6 text-primary\" />"
  print "          </div>"
  print "          <h3 className=\"text-2xl font-bold font-sans uppercase tracking-tight mb-4 relative z-10\">Luxurious Conditions</h3>"
  print "          <p className=\"text-surface/70 font-medium relative z-10\">Bring your productions to life with top sound engineers and world-class acoustics in a premium environment.</p>"
  print "        </div>"
  print "        <div className=\"aspect-square rounded-3xl border border-foreground/10 shadow-xl overflow-hidden relative group\">"
  print "          <img src=\"https://images.unsplash.com/photo-1621360841013-c76831f1628f?auto=format&fit=crop&q=80&w=800\" alt=\"Mixing Console\" className=\"w-full h-full object-cover grayscale-[20%] group-hover:grayscale-0 transition-all duration-500 group-hover:scale-105\" />"
  print "        </div>"
  print "        <div className=\"aspect-square rounded-3xl border border-foreground/10 shadow-xl bg-primary text-foreground p-8 flex flex-col justify-center items-center text-center group hover:-translate-y-2 transition-transform duration-300\">"
  print "          <div className=\"w-12 h-12 rounded-full bg-foreground/10 flex items-center justify-center mb-6\">"
  print "            <Globe className=\"w-6 h-6 text-foreground\" />"
  print "          </div>"
  print "          <h3 className=\"text-2xl font-bold font-sans uppercase tracking-tight mb-4\">Global Icons</h3>"
  print "          <p className=\"text-foreground/80 font-medium text-sm\">Sharing the same rooms as French Montana, Black Coffee, Diplo, Lost Frequencies, Robin Schulz, and more.</p>"
  print "        </div>"
  print ""
  print "        {/* Row 3 */}"
  print "        <div className=\"aspect-square rounded-3xl border border-foreground/10 shadow-xl overflow-hidden relative group\">"
  print "          <img src=\"https://images.unsplash.com/photo-1571266028243-3716f02d2d2e?auto=format&fit=crop&q=80&w=800\" alt=\"Microphone\" className=\"w-full h-full object-cover grayscale-[20%] group-hover:grayscale-0 transition-all duration-500 group-hover:scale-105\" />"
  print "        </div>"
  print "        <div className=\"aspect-square rounded-3xl border border-foreground/10 shadow-xl bg-white p-8 flex flex-col justify-center items-center text-center group hover:-translate-y-2 transition-transform duration-300\">"
  print "          <div className=\"w-12 h-12 rounded-full bg-primary/20 flex items-center justify-center mb-6\">"
  print "            <Music2 className=\"w-6 h-6 text-primary\" />"
  print "          </div>"
  print "          <h3 className=\"text-2xl font-bold font-sans uppercase tracking-tight mb-4\">Your Sound</h3>"
  print "          <p className=\"text-foreground/70 font-medium\">We don'\''t just release records — we develop artists and push boundaries.</p>"
  print "        </div>"
  print "        <div className=\"aspect-square rounded-3xl border border-foreground/10 shadow-xl overflow-hidden relative group\">"
  print "          <img src=\"https://images.unsplash.com/photo-1516280440502-8673a5a40733?auto=format&fit=crop&q=80&w=800\" alt=\"DJ Performance\" className=\"w-full h-full object-cover grayscale-[20%] group-hover:grayscale-0 transition-all duration-500 group-hover:scale-105\" />"
  print "        </div>"
  print "      </div>"
  print "    </section>"
  print "  );"
  print "};"
  print ""
}
{ print }
' > src/App_new.tsx && mv src/App_new.tsx src/App.tsx
